[package]
name = "basic64"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
phf = { version = "0.11", features = ["macros"] }

[dev-dependencies]
tempfile = "3"
